import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  realpathSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join, normalize, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { refreshClaudeCodeVersion } from "./src/version.js";

export const PACKAGE_NAME = "@ladbabynpm/picc-claude-shim";
export const EXTENSION_NAME = "picc-claude-shim";
export const SHIM_ROOT_FILE = "picc-claude-shim-root.txt";

const __filename = fileURLToPath(import.meta.url);
export const DEFAULT_SHIM_ROOT = dirname(__filename);

function defaultLog(...args) {
  process.stderr.write(`[picc-claude-shim/install] ${args.join(" ")}\n`);
}

function normalizedPath(path) {
  return normalize(resolve(path)).replace(/[\\/]+$/, "").toLowerCase();
}

function resolvedPath(path) {
  try {
    return normalizedPath(realpathSync(path));
  } catch {
    return normalizedPath(path);
  }
}

function sameDirectory(left, right) {
  return resolvedPath(left) === resolvedPath(right);
}

export function isPiManagedInstall(shimRoot) {
  const normalizedRoot = shimRoot.replace(/\\/g, "/").toLowerCase();
  return normalizedRoot.includes(`npm/node_modules/${PACKAGE_NAME.toLowerCase()}`);
}

export function launcherDirectory(agentDir) {
  return join(agentDir, "extensions", EXTENSION_NAME, "bin");
}

function writePosixLauncher(target, shimRoot) {
  const shimBin = join(shimRoot, "bin", "claude.js");
  const quote = `'${shimBin.replace(/'/g, "'\\''")}'`;
  const content = [
    "#!/usr/bin/env bash",
    "# Auto-generated by picc-claude-shim/install.js",
    "set -euo pipefail",
    `exec node ${quote} "$@"`,
    "",
  ].join("\n");
  writeFileSync(target, content);
  try {
    chmodSync(target, 0o755);
  } catch {
    // Windows permissions are best-effort only.
  }
}

function writeWindowsLauncher(targetDir, shimRoot) {
  const source = join(shimRoot, "bin", "claude.exe");
  if (!existsSync(source)) {
    throw new Error(
      `native launcher not found at ${source}; the published package must include bin/claude.exe`,
    );
  }

  copyFileSync(source, join(targetDir, "claude.exe"));
  // The native launcher reads this sidecar after it has been copied outside
  // the npm package. It points back to the package root, where the JS runtime
  // and TypeScript source live.
  writeFileSync(join(targetDir, SHIM_ROOT_FILE), `${resolve(shimRoot)}\n`, "utf8");
}

/**
 * Install a deterministic, explicitly-configurable launcher in pi's extension
 * directory. Nothing is placed on PATH and no third-party application files
 * are touched. A source checkout already linked as this extension reuses its
 * own bin directory instead of copying onto itself.
 */
export async function runInstaller({
  shimRoot = DEFAULT_SHIM_ROOT,
  agentDir = process.env.PI_CODING_AGENT_DIR ?? join(homedir(), ".pi", "agent"),
  platform = process.platform,
  fetchImpl,
  log = defaultLog,
} = {}) {
  const extensionDir = join(agentDir, "extensions", EXTENSION_NAME);
  const targetDir = launcherDirectory(agentDir);

  try {
    mkdirSync(targetDir, { recursive: true });

    if (sameDirectory(extensionDir, shimRoot)) {
      const launcher = platform === "win32"
        ? join(targetDir, "claude.exe")
        : join(targetDir, "claude");
      if (!existsSync(launcher)) {
        throw new Error(`source launcher not found at ${launcher}`);
      }
      log(`launcher already available: ${launcher}`);
    } else if (platform === "win32") {
      writeWindowsLauncher(targetDir, shimRoot);
      log(`Windows launcher installed: ${join(targetDir, "claude.exe")}`);
    } else {
      writePosixLauncher(join(targetDir, "claude"), shimRoot);
      log(`POSIX launcher installed: ${join(targetDir, "claude")}`);
    }

    try {
      const version = await refreshClaudeCodeVersion({ cacheDir: extensionDir, fetchImpl });
      log(`Claude Code release version cached: ${version}`);
    } catch (error) {
      log(`could not fetch the latest Claude Code release: ${error instanceof Error ? error.message : String(error)}; using the cached or bundled fallback version.`);
    }
    log("configure third-party applications with the path above; no PATH changes were made.");
    return true;
  } catch (error) {
    log(`could not create dedicated launcher: ${error instanceof Error ? error.message : String(error)}`);
    // The pi extension still loads from the npm package, so a launcher-copy
    // failure must not turn a safe package install into a failure.
    return true;
  }
}
