import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { delimiter, dirname, join, normalize, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const WRAPPER_MARKER = "picc-claude-shim-wrapper:v1";
export const PACKAGE_NAME = "@ladbabynpm/picc-claude-shim";

const __filename = fileURLToPath(import.meta.url);
export const DEFAULT_SHIM_ROOT = dirname(__filename);

function defaultLog(...args) {
  process.stderr.write(`[picc-claude-shim/install] ${args.join(" ")}\n`);
}

function normalizedPath(path) {
  return normalize(resolve(path)).replace(/[\\/]+$/, "").toLowerCase();
}

function pathEntries(pathValue) {
  if (!pathValue) return new Set();
  return new Set(
    pathValue
      .split(delimiter)
      .filter(Boolean)
      .map((entry) => normalizedPath(entry)),
  );
}

export function isPiManagedInstall(shimRoot) {
  const normalizedRoot = shimRoot.replace(/\\/g, "/").toLowerCase();
  return normalizedRoot.includes(`npm/node_modules/${PACKAGE_NAME.toLowerCase()}`);
}

export function pickBinDir({ homeDir, pathValue, makeDir = mkdirSync }) {
  const onPath = pathEntries(pathValue);
  const candidates = [join(homeDir, ".local", "bin"), join(homeDir, "bin")];

  for (const candidate of candidates) {
    if (!onPath.has(normalizedPath(candidate))) continue;
    try {
      makeDir(candidate, { recursive: true });
      return candidate;
    } catch {
      // Try the next user-local directory already available on PATH.
    }
  }
  return null;
}

function shellQuote(value) {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

function wrapperTargets(binDir) {
  return {
    cmd: join(binDir, "claude.cmd"),
    posix: join(binDir, "claude"),
    exe: join(binDir, "claude.exe"),
  };
}

function isOwnedWrapper(target) {
  try {
    const content = readFileSync(target);
    // Versions published before wrapper markers used this project-specific
    // identifier. Retaining it solely for upgrades lets old picc wrappers be
    // migrated without treating arbitrary Claude Code binaries as ours.
    return (
      content.includes(WRAPPER_MARKER) ||
      content.includes("picc-claude-shim") ||
      content.includes("pi-claude-shim")
    );
  } catch {
    return false;
  }
}

/**
 * Check every competing executable name before modifying any of them. This
 * prevents a partially-installed shim from taking precedence over a real
 * Claude Code installation in the same directory.
 */
export function preflightWrapperTargets(targets, { force = false, log = defaultLog } = {}) {
  const conflicts = [];
  for (const [kind, target] of Object.entries(targets)) {
    if (existsSync(target) && !isOwnedWrapper(target)) {
      conflicts.push(`${kind}: ${target}`);
    }
  }

  if (conflicts.length > 0 && !force) {
    log(
      "refusing to overwrite existing non-picc Claude wrapper(s):",
      conflicts.join(", "),
      "Run `node install.js --force` only if replacing them is intentional.",
    );
    return false;
  }
  return true;
}

function writeCmdShim(target, shimRoot) {
  const template = readFileSync(join(shimRoot, "bin", "claude.cmd"), "utf8");
  const shimBin = join(shimRoot, "bin", "claude.js");
  writeFileSync(target, template.replace("__SHIM_BIN_PLACEHOLDER__", shimBin));
  return "written";
}

function writePosixShim(target, shimRoot) {
  const shimBin = join(shimRoot, "bin", "claude.js");
  const content = [
    "#!/usr/bin/env bash",
    `# ${WRAPPER_MARKER}`,
    "# Auto-generated by picc-claude-shim/install.js",
    "set -euo pipefail",
    `exec node ${shellQuote(shimBin)} "$@"`,
    "",
  ].join("\n");
  writeFileSync(target, content);
  try {
    chmodSync(target, 0o755);
  } catch {
    // Windows permissions are best-effort only.
  }
  return "written";
}

function writeExeShim(target, shimRoot, log) {
  const source = join(shimRoot, "bin", "claude.exe");
  if (!existsSync(source)) {
    log(
      "native claude.exe not found; Windows hosts that spawn without a shell may require it. The published package must include a launcher built with `node scripts/build-exe.mjs`.",
    );
    return "skipped";
  }
  copyFileSync(source, target);
  return "written";
}

function describeOutcome(log, name, target, outcome) {
  if (outcome === "written") log(`installed ${name}: ${target}`);
  if (outcome === "reused") log(`re-used ${name}: ${target}`);
  if (outcome === "skipped") log(`skipped ${name}: ${target}`);
}

function updateSettings(settingsPath, localEntry, log) {
  let settings;
  try {
    settings = JSON.parse(readFileSync(settingsPath, "utf8"));
  } catch (error) {
    log(`could not read settings.json: ${error instanceof Error ? error.message : String(error)}; skipping registration.`);
    return false;
  }

  if (settings === null || typeof settings !== "object" || Array.isArray(settings)) {
    log("settings.json must contain an object; skipping registration.");
    return false;
  }
  const packages = settings.packages;
  if (packages === undefined) {
    settings.packages = [];
  } else if (!Array.isArray(packages)) {
    log("settings.json#packages is not an array; skipping registration.");
    return false;
  }

  if (settings.packages.some((entry) => entry === localEntry)) return true;
  settings.packages.push(localEntry);

  const tempPath = `${settingsPath}.${process.pid}.${Date.now()}.tmp`;
  try {
    writeFileSync(tempPath, `${JSON.stringify(settings, null, 2)}\n`, "utf8");
    renameSync(tempPath, settingsPath);
    log(`added ${localEntry} to settings.json#packages`);
    return true;
  } catch (error) {
    try {
      rmSync(tempPath, { force: true });
    } catch {
      // Preserve the original write error.
    }
    log(`failed to update settings.json: ${error instanceof Error ? error.message : String(error)}`);
    return false;
  }
}

function registerExtension({ shimRoot, agentDir, args, log }) {
  if (isPiManagedInstall(shimRoot) && !args.includes("--register-local")) {
    log("pi-managed install — settings.json registration left to pi; skipping.");
    return;
  }

  const settingsPath = join(agentDir, "settings.json");
  if (!existsSync(settingsPath)) {
    log(`settings.json not found at ${settingsPath} — skipping registration.`);
    return;
  }
  updateSettings(settingsPath, "extensions/picc-claude-shim", log);
}

/**
 * Install wrapper executables and, for a source checkout, optionally register
 * the local extension. Returns false only when wrapper ownership preflight
 * detects a non-picc Claude executable.
 */
export function runInstaller({
  args = process.argv.slice(2),
  shimRoot = DEFAULT_SHIM_ROOT,
  agentDir = process.env.PI_CODING_AGENT_DIR ?? join(homedir(), ".pi", "agent"),
  homeDir = homedir(),
  pathValue = process.env.PATH,
  platform = process.platform,
  force = args.includes("--force"),
  log = defaultLog,
} = {}) {
  registerExtension({ shimRoot, agentDir, args, log });

  const binDir = pickBinDir({ homeDir, pathValue });
  if (!binDir) {
    log(
      "no writable supported user bin directory is on PATH; no Claude wrapper was installed. Add ~/.local/bin or ~/bin to PATH, then run `node install.js` again.",
    );
    return true;
  }

  const targets = wrapperTargets(binDir);
  if (!preflightWrapperTargets(targets, { force, log })) return false;

  const cmdOutcome = writeCmdShim(targets.cmd, shimRoot);
  describeOutcome(log, "claude.cmd", targets.cmd, cmdOutcome);

  if (platform === "win32" && !process.env.PI_SHIM_POSIX) {
    describeOutcome(log, "claude", targets.posix, "skipped");
  } else {
    describeOutcome(log, "claude", targets.posix, writePosixShim(targets.posix, shimRoot));
  }

  if (platform === "win32") {
    describeOutcome(log, "claude.exe", targets.exe, writeExeShim(targets.exe, shimRoot, log));
  } else {
    describeOutcome(log, "claude.exe", targets.exe, "skipped");
  }

  log("verify with: claude --version");
  return true;
}
